import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={`${geistMono.className} flex flex-col h-screen justify-between`}>
        
          <header className="flex p-5 border m-4 rounded-xl justify-between">
            <div>
              <h1 className="text-xl font-bold text-center">
                <a href="/">Уроки по Next.js</a>
              </h1>
            </div>
            <div>
              <a href="/login">
                <h1 className="text-xl font-bold text-right">Sign In</h1>
              </a>
            </div>
          </header>

          <main className="flex-auto">{children}</main>

          <footer className="text-xl p-5 text-center font-bold bg-neutral-primary-soft rounded-xl shadow-xs border border-default m-4 ">whoisbubble - 2026</footer>

        </div>
      </body>
    </html>
  );
}
